apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: installplan-operator

resources:
  - ../../../base

configMapGenerator:
  - name: updateconfig
    files:
      - approvals/kubevirt-hyperconverged.yaml
      - approvals/local-storage-operator.yaml
      - approvals/metering-operator.yaml
      - approvals/piplines-operator-rh.yaml

generatorOptions:
  disableNameSuffixHash: true
